/**
 * Photography, generated by \`scripts/grade-photography.mjs\`.
 *
 * Never enlarged — the recorded dimensions are the real ones, so
 * \`next/image\` will not be asked to serve more pixels than exist.
 *
 * Do not edit by hand; re-run the script.
 */
export interface Plate {
  name: string;
  src: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photography = [
  {
    "name": "court-hero",
    "src": "/photography/court-hero.webp",
    "alt": "Finished African teak badminton court in a darkened hall, lit by a single pool of light",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAsAA4BaJQBOgCG/tfsCAAD++FGkwG9Jov6qLH6jR+LFYHcn/gOZnymzHLXOlcLeKAAA"
  },
  {
    "name": "court-lit",
    "src": "/photography/court-lit.webp",
    "alt": "Finished African teak badminton court under full sports lighting",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAsAA4BaJbACdAEO/+j4IAD+8YQHnOLUw5k22RWBQD0MByva4GVvuNog5Zdi1dPVfYAA"
  },
  {
    "name": "framework",
    "src": "/photography/framework.webp",
    "alt": "Interlocked pine timber framework, notched at every crossing, on shock pads over a concrete slab",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAgCdASoQAAsAA4BaJYwCdAD0jBQBrOAAAP7tB+6wBI42u6GxilCdSec9QBFz/sAsAA=="
  },
  {
    "name": "lighting",
    "src": "/photography/lighting.webp",
    "alt": "Two rows of linear fixtures running outboard of the sidelines down a badminton hall",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoQAAsAA4BaJYgCdAEOuqV08AAA/vK5h7ZJoPAfvJuus7Gj7ojmfWAXgAA="
  },
  {
    "name": "teak-detail",
    "src": "/photography/teak-detail.webp",
    "alt": "Close detail of polished African teak boards and a painted court line",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoQAAsAA4BaJbACdABhywAA/uz63ajliPivHN1+M0CV3e0Cc7mlz9fc8nA7M+Ltw/QXaEAA"
  },
  {
    "name": "installation",
    "src": "/photography/installation.webp",
    "alt": "Teak flooring being blind-nailed with a pneumatic nailer over the pine framework",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoQAAsAA4BaJbACdADdLAoHOLcAAP7s3hsDkjclSv7oVKc2UhfwtLzTf3Y48SYA6DSzxgGwAAA="
  },
  {
    "name": "tool-shock-pad-nailer",
    "src": "/photography/tool-shock-pad-nailer.webp",
    "alt": "Pneumatic straight-magazine nailer, air line coupled, used to fix the shock pad rubber to the pine",
    "width": 880,
    "height": 880,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQABAAA4BaJZwAAgWEdSkHAAD+OpIKMH3q52nDtYkVtQneGjZvSNt7Dwz4AA=="
  },
  {
    "name": "tool-framework-coil-nailer",
    "src": "/photography/tool-framework-coil-nailer.webp",
    "alt": "Pneumatic coil nailer with its coil magazine on the side, used to fix the interlocked pine framework",
    "width": 1052,
    "height": 1052,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQABAAA4BaJQBOgBj57wlzHsAA/tHZS7E0vBYvyoag4MdSFwu9Xm+TbSrqrxyvRG1+v+Jr5khNAAAA"
  },
  {
    "name": "tool-flooring-cleat-nailer",
    "src": "/photography/tool-flooring-cleat-nailer.webp",
    "alt": "Stand-up hardwood flooring cleat nailer, its angled shoe set to register on a board tongue",
    "width": 643,
    "height": 643,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABwAQCdASoQABAAA4BaJZQAAT/4OgD+qX3j0kdRTnbOISRjECvPSrXQEFz/p7CHAAA="
  },
  {
    "name": "site-timber-delivery",
    "src": "/photography/site-timber-delivery.webp",
    "alt": "Bundles of sawn teak stacked in a finished room, waiting to be laid",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoQAAwAA4BaJZwAAuaR06EAAP2bpD6Hak5EK4SAAaW9KY/6sMBRd44AAAA="
  },
  {
    "name": "site-framework-going-down",
    "src": "/photography/site-framework-going-down.webp",
    "alt": "Pine members being set out across a hall floor, timber stacked alongside",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAwAA4BaJZwCdADydN98AAD+72d20jNbAI16dgoQQwz9fuqkgAAA"
  },
  {
    "name": "site-framework-run",
    "src": "/photography/site-framework-run.webp",
    "alt": "The framework running the length of a hall, boards following behind it",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAwAA4BaJZwAAu17t0H6wAD+7FfVUQC+TmauvDS0YZAmtdO726jgAAA="
  },
  {
    "name": "site-deck-partial",
    "src": "/photography/site-deck-partial.webp",
    "alt": "Deck part laid in a dark-clad hall with clerestory windows above",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAwAA4BaJZQAApKyg5aqAAD+0Lk1L89HvXpzM6PQVcnW+T1IDwAA"
  },
  {
    "name": "site-deck-laid",
    "src": "/photography/site-deck-laid.webp",
    "alt": "A hall fully decked in teak, before sanding and finish",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAAAQAgCdASoQAAwAA4BaJZwAAucLILY1SLMAAP70KGBD8pDj2aWcbBsNbcwAAA=="
  },
  {
    "name": "site-squash-court",
    "src": "/photography/site-squash-court.webp",
    "alt": "Finished squash court in maple, red lines to the front wall",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACQAQCdASoQAAwAA4BaJZQAAhJBtUAA/tHW5GXJBlM/4L0mArRrXtMU/gKZ7cFAAAA="
  },
  {
    "name": "site-finished-room",
    "src": "/photography/site-finished-room.webp",
    "alt": "Finished timber floor running out to the doorway of a smaller room",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAwAA4BaJQBOgBti2EoAAP7SSGGvMPjdB6DQBQIqVWEOtpsBUpOu7PhHlPJp7TP6AAAA"
  },
  {
    "name": "site-finished-daylight",
    "src": "/photography/site-finished-daylight.webp",
    "alt": "A finished floor under daylight from a full wall of windows",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAAAQAgCdASoQAAwAA4BaJZQCdAEPDG94WTgAAP7lIKMWB0sJbDU/Hgbx1qGgoAAA"
  },
  {
    "name": "site-finished-gloss",
    "src": "/photography/site-finished-gloss.webp",
    "alt": "The finish reading the ceiling line back across a completed floor",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAwAA4BaJQBdgBtl+LehAAD+8WLc0SXt88pIFfB/fkfvupaDymZzqAA="
  },
  {
    "name": "site-court-lines",
    "src": "/photography/site-court-lines.webp",
    "alt": "Markings set out on a completed teak court, fixtures lit above",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoQAAwAA4BaJYwCdAD0RwFdxAwAAP71zTuRb3K8WmRZfAzShPdbo6wkngNTAAAA"
  },
  {
    "name": "site-court-nets",
    "src": "/photography/site-court-nets.webp",
    "alt": "Nets up on a finished court, a blue-clad hall around it",
    "width": 1240,
    "height": 930,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoQAAwAA4BaJQBOgCG3jZOblQAA/vM5OVJM7GUkmQsDza9EY0f/h1WWX9OFAQAA"
  },
  {
    "name": "site-hall-lighting",
    "src": "/photography/site-hall-lighting.webp",
    "alt": "Two fixture rows running the length of a steel-framed hall",
    "width": 1240,
    "height": 697,
    "blurDataURL": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoQAAkAA4BaJZwAAxZf5XEC6AD+8Ri/r0I06Ap12C3CLj8AAAA="
  },
  {
    "name": "site-lighting-fitout",
    "src": "/photography/site-lighting-fitout.webp",
    "alt": "Fixtures in a fitted-out ceiling, access still up",
    "width": 1240,
    "height": 697,
    "blurDataURL": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACQAQCdASoQAAkAA4BaJZwAAuabfFAA/tHvx0D63TsB4ydUmy/GcCAA"
  },
  {
    "name": "site-mat-detail",
    "src": "/photography/site-mat-detail.webp",
    "alt": "A tournament mat rolled over a finished court",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAwCdASoQABUAPu1iqk4ppaQiMAgBMB2JQBhQA8Krb/ljEotIAAD+gHvJikOFUf/7yA6PGwy8OPmR6i6097UcAAA="
  },
  {
    "name": "site-match-play",
    "src": "/photography/site-match-play.webp",
    "alt": "Match play under a full installation",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoQABUAPu1krU2ppaSiMAgBMB2JYwAAYfZ6/LHB47pC5AAA/uP+JPNqhyJrLm3PLr03ra38w5lTNkhfCzTf0l0uQtJyYOAA"
  }
] as const satisfies readonly Plate[];

export const plate = (name: string): Plate =>
  photography.find((p) => p.name === name) ?? photography[0];
