/**
 * Photography, generated by \`scripts/grade-photography.mjs\`.
 *
 * Never enlarged — the recorded dimensions are the real ones, so
 * \`next/image\` will not be asked to serve more pixels than exist.
 *
 * Do not edit by hand; re-run the script.
 */
export interface Plate {
  name: string;
  src: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photography = [
  {
    "name": "court-hero",
    "src": "/photography/court-hero.webp",
    "alt": "Finished African teak badminton court in a darkened hall, lit by a single pool of light",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQAAsAA4BaJQBOgCG/tfsCAAD++FGkwG9Jov6qLH6jR+LFYHcn/gOZnym8VV3tmEQlG5gAAAA="
  },
  {
    "name": "court-lit",
    "src": "/photography/court-lit.webp",
    "alt": "Finished African teak badminton court under full sports lighting",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoQAAsAA4BaJbACdAEO//3R4TgAAP7xhAec7wJ5GfmH/XwI+WFJzMES90R6/0+zhKQIGcc6CAAAAA=="
  },
  {
    "name": "framework",
    "src": "/photography/framework.webp",
    "alt": "Interlocked pine timber framework, notched at every crossing, on shock pads over a concrete slab",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAgCdASoQAAsAA4BaJYwCdAD0i361+9IAAP7tB+58E8WYyHtRh65howlvnyLn/YBYAA=="
  },
  {
    "name": "lighting",
    "src": "/photography/lighting.webp",
    "alt": "Two rows of linear fixtures running outboard of the sidelines down a badminton hall",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoQAAsAA4BaJYgCdAEN3MGwWAAA/vK5h7ZMUkT48+tKAV0YqvWuZ9YBeAAAAA=="
  },
  {
    "name": "teak-detail",
    "src": "/photography/teak-detail.webp",
    "alt": "Close detail of polished African teak boards and a painted court line",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAsAA4BaJbACdADr7OAAAP7s+t2H0ua8eLw25MxoPDaBOdzS5+vueTge5fi7cP0F2hAA"
  },
  {
    "name": "installation",
    "src": "/photography/installation.webp",
    "alt": "Teak flooring being blind-nailed with a pneumatic nailer over the pine framework",
    "width": 1240,
    "height": 826,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAsAA4BaJbACdADc9ql0SAAA/u0MC3z1e7IdOzvzW4W1oYMrSoabqd2/uxx4kwB0GlnjANgAAA=="
  },
  {
    "name": "tool-shock-pad-nailer",
    "src": "/photography/tool-shock-pad-nailer.webp",
    "alt": "Pneumatic straight-magazine nailer, air line coupled, used to fix the shock pad rubber to the pine",
    "width": 880,
    "height": 880,
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoQABAAA4BaJZwAAcIEHhfAAP46kg94FKvTV6hnLGcNEMhCsf55lpYZo467b9bcA3oAAA=="
  },
  {
    "name": "tool-framework-coil-nailer",
    "src": "/photography/tool-framework-coil-nailer.webp",
    "alt": "Pneumatic coil nailer with its coil magazine on the side, used to fix the interlocked pine framework",
    "width": 1052,
    "height": 1052,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQABAAA4BaJQBOgBh2jzayzgAA/sGW2g51qCSU5tHYdgf9gn1TXjH40U7I0Vb7dHS35YYTNAdEgAAA"
  },
  {
    "name": "tool-flooring-cleat-nailer",
    "src": "/photography/tool-flooring-cleat-nailer.webp",
    "alt": "Stand-up hardwood flooring cleat nailer, its angled shoe set to register on a board tongue",
    "width": 643,
    "height": 643,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABwAQCdASoQABAAA4BaJZQAAT/4OgD+qX3jnwMfJJ98mkvl6iZuP7Eouc6p9PYQ4AA="
  }
] as const satisfies readonly Plate[];

export const plate = (name: string): Plate =>
  photography.find((p) => p.name === name) ?? photography[0];
