/**
 * Imagery, generated by \`scripts/build-plates.mjs\`.
 *
 * Rendered from the site's own 3D scene rather than photographed. The brochure
 * photography was print-resolution (~780px) and fell apart at any useful size;
 * these are sharp at 2000px, carry no licensing risk, and show RACEON's actual
 * build-up rather than a stock hall belonging to someone else.
 *
 * Do not edit by hand; re-run the script.
 */
export interface Plate {
  name: string;
  src: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photography = [
  {
    "name": "court-lit",
    "src": "/photography/court-lit.webp",
    "alt": "Finished RACEON African teak badminton court under 150W lighting",
    "width": 2000,
    "height": 1250,
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQAAoAA4BaJQBOgCG8qNv+PhwA/vbiwf/H15wxKNwj8NN+2ADObK0kE2AqdJ9aJDkAAA=="
  },
  {
    "name": "court-hero",
    "src": "/photography/court-hero.webp",
    "alt": "RACEON teak badminton court in a darkened hall",
    "width": 2000,
    "height": 1250,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoQAAoAA4BaJYwC7AEPDuaIfAAA/vfF0tw50iG28TW07iuaJKO8yWpHYYqAAA=="
  },
  {
    "name": "framework",
    "src": "/photography/framework.webp",
    "alt": "RACEON's interlocked pine framework, notched at every crossing",
    "width": 2000,
    "height": 1250,
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoQAAoAA4BaJQBOgCPtv3nJAAD+8X4NWDC5PIDDHxp/1w/14aZAAA=="
  },
  {
    "name": "lighting",
    "src": "/photography/lighting.webp",
    "alt": "RACEON 150W fixtures running outboard of the sidelines",
    "width": 2000,
    "height": 1250,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAoAA4BaJQAAXPD+La00YgD+95XruridRQUS3XIRV+lzxet2lAAA"
  }
] as const satisfies readonly Plate[];

export const plate = (name: string): Plate =>
  photography.find((p) => p.name === name) ?? photography[0];
