/**
 * Turns rendered 3D plates into the site's image set.
 *
 * The brochure photography is print-compressed at ~780px and could not be shown
 * at any size that mattered without falling apart. These plates come out of the
 * site's own WebGL scene at 2400x1500, so they are sharp, they carry no
 * licensing risk, and — unlike stock — they show RACEON's actual build-up
 * rather than someone else's hall.
 *
 * Re-render the sources by driving the site with the ?render=full override and
 * capturing the canvas with the DOM hidden; then run this.
 *
 * Usage: node scripts/build-plates.mjs <plate-dir>
 */
import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const SRC = process.argv[2];
if (!SRC) {
  console.error("usage: node scripts/build-plates.mjs <plate-dir>");
  process.exit(1);
}

const OUT = "public/photography";
const WIDTH = 2000;

const PLATES = [
  {
    file: "court-lit.png",
    name: "court-lit",
    alt: "Finished RACEON African teak badminton court under 150W lighting",
  },
  {
    file: "court-hero.png",
    name: "court-hero",
    alt: "RACEON teak badminton court in a darkened hall",
  },
  {
    file: "framework.png",
    name: "framework",
    alt: "RACEON's interlocked pine framework, notched at every crossing",
  },
  {
    file: "lighting.png",
    name: "lighting",
    alt: "RACEON 150W fixtures running outboard of the sidelines",
  },
];

/** A faint vignette so a plate sits into the page rather than on top of it. */
function vignette(w, h) {
  return Buffer.from(
    `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
       <defs>
         <radialGradient id="v" cx="50%" cy="48%" r="78%">
           <stop offset="52%" stop-color="#ffffff" stop-opacity="1"/>
           <stop offset="100%" stop-color="#0c0710" stop-opacity="0.34"/>
         </radialGradient>
       </defs>
       <rect width="${w}" height="${h}" fill="url(#v)"/>
     </svg>`,
  );
}

await mkdir(OUT, { recursive: true });
const manifest = [];

for (const plate of PLATES) {
  const input = path.join(SRC, plate.file);
  const resized = sharp(input).resize({ width: WIDTH, withoutEnlargement: true });
  const { width: w = 0, height: h = 0 } = await resized
    .clone()
    .toBuffer({ resolveWithObject: true })
    .then((r) => r.info);

  const outfile = path.join(OUT, `${plate.name}.webp`);
  await resized
    .composite([{ input: vignette(w, h), blend: "multiply" }])
    .webp({ quality: 84, effort: 6 })
    .toFile(outfile);

  const placeholder = await sharp(outfile)
    .resize(16)
    .blur(1.4)
    .webp({ quality: 40 })
    .toBuffer();

  manifest.push({
    name: plate.name,
    src: `/photography/${plate.name}.webp`,
    alt: plate.alt,
    width: w,
    height: h,
    blurDataURL: `data:image/webp;base64,${placeholder.toString("base64")}`,
  });

  console.log(`${plate.name}.webp  ${w}x${h}`);
}

await writeFile(
  "src/content/photography.ts",
  `/**
 * Imagery, generated by \\\`scripts/build-plates.mjs\\\`.
 *
 * Rendered from the site's own 3D scene rather than photographed. The brochure
 * photography was print-resolution (~780px) and fell apart at any useful size;
 * these are sharp at 2000px, carry no licensing risk, and show RACEON's actual
 * build-up rather than a stock hall belonging to someone else.
 *
 * Do not edit by hand; re-run the script.
 */
export interface Plate {
  name: string;
  src: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photography = ${JSON.stringify(manifest, null, 2)} as const satisfies readonly Plate[];

export const plate = (name: string): Plate =>
  photography.find((p) => p.name === name) ?? photography[0];
`,
);
console.log("wrote src/content/photography.ts");
